// The jujuapidochtml renders JSON output from jujuapidoc into
// HTML.
//
// A copy of the output of jujuapidoc as of Juju revision a0fffc4169831e
// can be found at http://rogpeppe-scratch.s3.amazonaws.com/juju-api.json
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"html/template"
	"io/ioutil"
	"log"
	"os"

	"github.com/rogpeppe/apicompat/jsontypes"

	"github.com/rogpeppe/misc/cmd/jujuapidoc/apidoc"
)

var htmlTmpl = `
<html>
<head>
<style>
	body {
		font-family: Ubuntu Light, sans-serif;
		padding: 25px;
	}
	h2 a {
		color: black;
		text-decoration: none;
	}
	h2 a:hover {
		text-decoration: underline;
	}
	h2 + p {
		padding-left: 25px;
	}
	tr:nth-child(even) {
		background-color: #f1f1f1;
	}
	td {
		vertical-align: top;
		padding: 10px;
	}
</style>
<title>Juju API docs (autogenerated)</title>
</head>
<body>
<h1>Juju API facades</h1>
{{range .Facades}}
	<h2 id="{{.Name}}"><a href="#{{.Name}}">{{.Name}}</a></h2>
	<p>{{.Doc}}</p>
	<table>
		<tr>
			<th>Name</th>
			<th>Params</th>
			<th>Results</th>
			<th>Description</th>
		</tr>
		{{range .Methods}}
			<tr>
				<td>{{.Name}}</td>
				<td>{{.Param | typeLink}}</td>
				<td>{{.Result | typeLink}}</td>
				<td>{{.Doc}}</td>
			</tr>
		{{end}}
	</table>
{{end}}
</body>
</html>
`

var clientFacades = map[string]bool{
	"Action": true,
	"AllModelWatcher": true,
	"AllWatcher": true,
	"Annotations": true,
	"Application": true,
	"Backups": true,
	"Block": true,
	"Charms": true,
	"Client": true,
	"Cloud": true,
	"Controller": true,
	"HighAvailability": true,
	"ImageManager": true,
	"ImageMetadata": true,
	"KeyManager": true,
	"MachineManager": true,
	"MetricsDebug": true,
	"ModelConfig": true,
	"ModelManager": true,
	"Pinger": true,
	"Spaces": true,
	"SSHClient": true,
	"Storage": true,
	"Subnets": true,
	"UserManager": true,
	"Admin": true,
}

func main() {
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "usage: jujuapidochtml api.json\n")
		os.Exit(2)
	}
	flag.Parse()

	if flag.NArg() != 1 {
		flag.Usage()
	}

	data, err := ioutil.ReadFile(flag.Arg(0))
	if err != nil {
		log.Fatal(err)
	}
	var info *apidoc.Info
	if err := json.Unmarshal(data, &info); err != nil {
		log.Fatal(err)
	}
	facades := make([]apidoc.FacadeInfo, 0, len(info.Facades))
	for _, f := range info.Facades {
		if !clientFacades[f.Name] {
			facades = append(facades, f)
		}
	}
	info.Facades = facades
//	c := 0
//	for _, f := range info.Facades {
//		c += len(f.Methods)
//	}
//	fmt.Println(c)
//	return

	t, err := template.New("").Funcs(tmplFuncs).Parse(htmlTmpl)
	if err != nil {
		log.Fatal(err)
	}
	if err := t.Execute(os.Stdout, info); err != nil {
		log.Fatal(err)
	}
}

var tmplFuncs = template.FuncMap{
	"typeLink": func(t *jsontypes.Type) template.HTML {
		if t == nil {
			return "n/a"
		}
		link := fmt.Sprintf(`<a href="https://godoc.org/%s">%s</a>`, t.Name, t.Name.Name())
		return template.HTML(link)
	},
}
