package linedrawer

import (
	"encoding/binary"
	"image/color"
)

type hexColor uint32

func (c hexColor) RGBA() (r, g, b, a uint32) {
	return c.rgba().RGBA()
}

func (c hexColor) rgba() color.RGBA {
	var buf [4]uint8
	binary.BigEndian.PutUint32(buf[:], uint32(c))
	return color.RGBA{
		R: buf[1],
		G: buf[2],
		B: buf[3],
		A: 0xff,
	}
}

// From https://css-tricks.com/snippets/css/named-colors-and-hex-equivalents/

const (
	colorAliceBlue            = hexColor(0xF0F8FF)
	colorAntiqueWhite         = hexColor(0xFAEBD7)
	colorAqua                 = hexColor(0x00FFFF)
	colorAquamarine           = hexColor(0x7FFFD4)
	colorAzure                = hexColor(0xF0FFFF)
	colorBeige                = hexColor(0xF5F5DC)
	colorBisque               = hexColor(0xFFE4C4)
	colorBlack                = hexColor(0x000000)
	colorBlanchedAlmond       = hexColor(0xFFEBCD)
	colorBlue                 = hexColor(0x0000FF)
	colorBlueViolet           = hexColor(0x8A2BE2)
	colorBrown                = hexColor(0xA52A2A)
	colorBurlyWood            = hexColor(0xDEB887)
	colorCadetBlue            = hexColor(0x5F9EA0)
	colorChartreuse           = hexColor(0x7FFF00)
	colorChocolate            = hexColor(0xD2691E)
	colorCoral                = hexColor(0xFF7F50)
	colorCornflowerBlue       = hexColor(0x6495ED)
	colorCornsilk             = hexColor(0xFFF8DC)
	colorCrimson              = hexColor(0xDC143C)
	colorCyan                 = hexColor(0x00FFFF)
	colorDarkBlue             = hexColor(0x00008B)
	colorDarkCyan             = hexColor(0x008B8B)
	colorDarkGoldenRod        = hexColor(0xB8860B)
	colorDarkGray             = hexColor(0xA9A9A9)
	colorDarkGrey             = hexColor(0xA9A9A9)
	colorDarkGreen            = hexColor(0x006400)
	colorDarkKhaki            = hexColor(0xBDB76B)
	colorDarkMagenta          = hexColor(0x8B008B)
	colorDarkOliveGreen       = hexColor(0x556B2F)
	colorDarkorange           = hexColor(0xFF8C00)
	colorDarkOrchid           = hexColor(0x9932CC)
	colorDarkRed              = hexColor(0x8B0000)
	colorDarkSalmon           = hexColor(0xE9967A)
	colorDarkSeaGreen         = hexColor(0x8FBC8F)
	colorDarkSlateBlue        = hexColor(0x483D8B)
	colorDarkSlateGray        = hexColor(0x2F4F4F)
	colorDarkSlateGrey        = hexColor(0x2F4F4F)
	colorDarkTurquoise        = hexColor(0x00CED1)
	colorDarkViolet           = hexColor(0x9400D3)
	colorDeepPink             = hexColor(0xFF1493)
	colorDeepSkyBlue          = hexColor(0x00BFFF)
	colorDimGray              = hexColor(0x696969)
	colorDimGrey              = hexColor(0x696969)
	colorDodgerBlue           = hexColor(0x1E90FF)
	colorFireBrick            = hexColor(0xB22222)
	colorFloralWhite          = hexColor(0xFFFAF0)
	colorForestGreen          = hexColor(0x228B22)
	colorFuchsia              = hexColor(0xFF00FF)
	colorGainsboro            = hexColor(0xDCDCDC)
	colorGhostWhite           = hexColor(0xF8F8FF)
	colorGold                 = hexColor(0xFFD700)
	colorGoldenRod            = hexColor(0xDAA520)
	colorGray                 = hexColor(0x808080)
	colorGrey                 = hexColor(0x808080)
	colorGreen                = hexColor(0x008000)
	colorGreenYellow          = hexColor(0xADFF2F)
	colorHoneyDew             = hexColor(0xF0FFF0)
	colorHotPink              = hexColor(0xFF69B4)
	colorIndianRed            = hexColor(0xCD5C5C)
	colorIndigo               = hexColor(0x4B0082)
	colorIvory                = hexColor(0xFFFFF0)
	colorKhaki                = hexColor(0xF0E68C)
	colorLavender             = hexColor(0xE6E6FA)
	colorLavenderBlush        = hexColor(0xFFF0F5)
	colorLawnGreen            = hexColor(0x7CFC00)
	colorLemonChiffon         = hexColor(0xFFFACD)
	colorLightBlue            = hexColor(0xADD8E6)
	colorLightCoral           = hexColor(0xF08080)
	colorLightCyan            = hexColor(0xE0FFFF)
	colorLightGoldenRodYellow = hexColor(0xFAFAD2)
	colorLightGray            = hexColor(0xD3D3D3)
	colorLightGrey            = hexColor(0xD3D3D3)
	colorLightGreen           = hexColor(0x90EE90)
	colorLightPink            = hexColor(0xFFB6C1)
	colorLightSalmon          = hexColor(0xFFA07A)
	colorLightSeaGreen        = hexColor(0x20B2AA)
	colorLightSkyBlue         = hexColor(0x87CEFA)
	colorLightSlateGray       = hexColor(0x778899)
	colorLightSlateGrey       = hexColor(0x778899)
	colorLightSteelBlue       = hexColor(0xB0C4DE)
	colorLightYellow          = hexColor(0xFFFFE0)
	colorLime                 = hexColor(0x00FF00)
	colorLimeGreen            = hexColor(0x32CD32)
	colorLinen                = hexColor(0xFAF0E6)
	colorMagenta              = hexColor(0xFF00FF)
	colorMaroon               = hexColor(0x800000)
	colorMediumAquaMarine     = hexColor(0x66CDAA)
	colorMediumBlue           = hexColor(0x0000CD)
	colorMediumOrchid         = hexColor(0xBA55D3)
	colorMediumPurple         = hexColor(0x9370D8)
	colorMediumSeaGreen       = hexColor(0x3CB371)
	colorMediumSlateBlue      = hexColor(0x7B68EE)
	colorMediumSpringGreen    = hexColor(0x00FA9A)
	colorMediumTurquoise      = hexColor(0x48D1CC)
	colorMediumVioletRed      = hexColor(0xC71585)
	colorMidnightBlue         = hexColor(0x191970)
	colorMintCream            = hexColor(0xF5FFFA)
	colorMistyRose            = hexColor(0xFFE4E1)
	colorMoccasin             = hexColor(0xFFE4B5)
	colorNavajoWhite          = hexColor(0xFFDEAD)
	colorNavy                 = hexColor(0x000080)
	colorOldLace              = hexColor(0xFDF5E6)
	colorOlive                = hexColor(0x808000)
	colorOliveDrab            = hexColor(0x6B8E23)
	colorOrange               = hexColor(0xFFA500)
	colorOrangeRed            = hexColor(0xFF4500)
	colorOrchid               = hexColor(0xDA70D6)
	colorPaleGoldenRod        = hexColor(0xEEE8AA)
	colorPaleGreen            = hexColor(0x98FB98)
	colorPaleTurquoise        = hexColor(0xAFEEEE)
	colorPaleVioletRed        = hexColor(0xD87093)
	colorPapayaWhip           = hexColor(0xFFEFD5)
	colorPeachPuff            = hexColor(0xFFDAB9)
	colorPeru                 = hexColor(0xCD853F)
	colorPink                 = hexColor(0xFFC0CB)
	colorPlum                 = hexColor(0xDDA0DD)
	colorPowderBlue           = hexColor(0xB0E0E6)
	colorPurple               = hexColor(0x800080)
	colorRed                  = hexColor(0xFF0000)
	colorRosyBrown            = hexColor(0xBC8F8F)
	colorRoyalBlue            = hexColor(0x4169E1)
	colorSaddleBrown          = hexColor(0x8B4513)
	colorSalmon               = hexColor(0xFA8072)
	colorSandyBrown           = hexColor(0xF4A460)
	colorSeaGreen             = hexColor(0x2E8B57)
	colorSeaShell             = hexColor(0xFFF5EE)
	colorSienna               = hexColor(0xA0522D)
	colorSilver               = hexColor(0xC0C0C0)
	colorSkyBlue              = hexColor(0x87CEEB)
	colorSlateBlue            = hexColor(0x6A5ACD)
	colorSlateGray            = hexColor(0x708090)
	colorSlateGrey            = hexColor(0x708090)
	colorSnow                 = hexColor(0xFFFAFA)
	colorSpringGreen          = hexColor(0x00FF7F)
	colorSteelBlue            = hexColor(0x4682B4)
	colorTan                  = hexColor(0xD2B48C)
	colorTeal                 = hexColor(0x008080)
	colorThistle              = hexColor(0xD8BFD8)
	colorTomato               = hexColor(0xFF6347)
	colorTurquoise            = hexColor(0x40E0D0)
	colorViolet               = hexColor(0xEE82EE)
	colorWheat                = hexColor(0xF5DEB3)
	colorWhite                = hexColor(0xFFFFFF)
	colorWhiteSmoke           = hexColor(0xF5F5F5)
	colorYellow               = hexColor(0xFFFF00)
	colorYellowGreen          = hexColor(0x9ACD32)
)
